# 项目相关配置
draw-server:
  # 名称
  name: '@service.id@'

server:
  port: 13886
  tomcat:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
      # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
      # 设定每个region的buffer数 每个区分配的buffer数量 , 所以pool的大小是buffer-size * buffers-per-region
      # buffers-per-region: 1024
    # 设定堆外内存 是否分配的直接内存
    direct-buffers: true
    accesslog:
      enabled: false  #是否开启access log，默认: false
      attern: '%t %a "%r" %s (%D ms)'
      dir: log #设定access log 的目录.
    access-log-dir: '@log.dir@' #设定Undertow access log 的目录，默认: logs
    access-log-pattern: common #设定access logs的格式，默认:

# 日志配置
logging:
  level:
    com.tc.draw.api.*.mapper.*: '@log.level@'

# Spring配置
spring:
  application:
    name: '@service.id@'
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  20MB
      # 设置总上传的文件大小
      max-request-size:  180MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: '@redis.host@'
    # 端口，默认为6379
    port: '@redis.port@'
    # 密码
    password: '@redis.password@'
    # 连接超时时间
    timeout: 10s



  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
    url: jdbc:mysql://@mysql.jdbc@?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: '@mysql.username@'
    password: '@mysql.password@'


# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌秘钥
  secret: weweefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 120

# MyBatis配置
mybatis:
  configuration:
    cacheEnabled: true # 全局映射器启用缓存
    useGeneratedKeys: true #  允许 JDBC 支持自动生成主键
    mapUnderscoreToCamelCase: true # 驼峰式命名
    defaultExecutorType: REUSE # 配置默认的执行器



# Swagger配置
swagger:
  enable: true

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes:
  # 匹配链接
  urlPatterns: /system/*,/monitor/*

